### PR TITLE
Remove forward slash from container name

### PR DESCRIPTION
**Pull request by nathanpower**
Propose to remove forward slash from container name

### CODE REVIEW

**Comment by funkymonkeymonk** [comment]
:+1: We would love to have this PR merged for Librato compatibility.

**Comment by kiyoto** [comment]
Done. @funkymonkeymonk would you be interested in becoming a maintainer? I barely have time these days to tinker with Docker or Fluentd, and you might be a better person to be maintaining this going forward =)

**Comment by funkymonkeymonk** [comment]
@kiyoto More than happy to.

**Comment by kiyoto** [comment]
@funkymonkeymonk Cool. You are now a co-maintainer of this project!

**Pull request merged**
